spring:
  application:
    name: hr
  profiles:
    active: smart
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:postgresql://localhost:5432/hr
    username: postgres
    password: uborka
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss

hr:
  salary:
    def:
      percent: 5
    smart:
      limits:
        1: 1
        2.5: 2
        5: 5
        10: 10
        7.5: 8

